/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:68e37eba-aff0-4191-8916-276d414ccc0f",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_rEC4pMjM0",
    "aws_user_pools_web_client_id": "68pqffm9vqn4u0e28cgto4p8em",
    "oauth": {}
};
    

export default awsmobile;
